package calc_val;


/**
* calc_val/calcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Friday, May 6, 2022 3:53:00 AM PDT
*/

public interface calcOperations 
{
  float getHomeLoan ();
  float getPersonalLoan ();
  float getCarLoan ();
  float getGoldLoan ();
} // interface calcOperations
